### ISSUE TITLE
Embedded images are not extracted

### ISSUE THREAD

**Issue by dmitrym0** [panicsteve/blogging-with-bear#3]
Love project, thanks for sharing!

I have some embedded images in Bear that don't get extracted:

1. create a note and either drag or paste an image into it
2. run `bear-export.php`

Expected: image gets extracted from the note
Actual: no image. Although there is a reference to the image in there.

**Comment by panicsteve** [comment]
So, images are in limbo at the moment!

An earlier version of this script required you to do a manual "export" from Bear -- the advantage to this was it included the images, but the disadvantage was it wasn't automated; you had to go into Bear's menus and do it yourself.

The script as it stands today does not extract images from Bear, because I haven't stopped to figure out where and how they're stored.  They're probably just files in the app's container somewhere, but I'm already uncomfortable making assumptions about Bear's SQLite database structure, and trawling around for images would just make it more fragile.

Ideally, there'd be an officially supported way for a script to request an export from Bear, without user interaction.  Then we'd have a nice separation of responsibilities, images would work, and we wouldn't have to worry about a future version of Bear breaking this script.

It might be more likely to happen if individual Bear users contact the developer to request such a feature, rather than just me, so if you feel like sending a short, polite email to them, maybe we can make it happen!

**Comment by dmitrym0** [comment]
Hello Steve,

I agree that an official way is preferable to anything home brewed, so I'm going to propose the following:

1. A hacky way to extract images [right now](https://www.youtube.com/watch?v=c9EBhaULToU) (see pull request #4)
2. Getting in touch with the devs and asking for an official way to exact images. In my experience, they are willing to discuss things at least.

**Comment by panicsteve** [comment]
I merged your PR (thank you!).  I had a brief conversation with the Bear devs on Twitter about getting an official programmatic way export a set of notes, but it might be more effective if everyone who is interested in this contacts them individually as well.

**Comment by dmitrym0** [comment]
Thanks Steve!
